In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf


tf.__version__

#imported dataset with pandas
dataset = pd.read_excel('student-mat-edited.xlsx')
x = dataset.iloc[:, :-1].values #variables
y = dataset.iloc[:, -1].values #Grades output 1-20 scale

print(x)
print(y)


#splitting data sets into training and test sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

#initialize ANN as the sequential layers
ann = tf.keras.models.Sequential()

#adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))

#adding the second hidden layer
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))

#adding the output layer
ann.add(tf.keras.layers.Dense(units=1))

#training the ANN
#compiling the ANN 
#optimizer adam is a good optimizer for gradient descent
#loss is the mean square error
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

#training the ANN model on the Training set
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)


#predicting the results of the test set
y_pred = ann.predict(x_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[ 2  2  0 ...  1  3  6]
 [ 1  2  0 ...  1  3  4]
 [ 1  2  3 ...  3  3 10]
 ...
 [ 1  1  3 ...  3  3  3]
 [ 3  1  0 ...  4  5  0]
 [ 1  1  0 ...  3  5  5]]
[ 6  6 10 15 10 15 11  6 19 15  9 12 14 11 16 14 14 10  5 10 15 15 16 12
  8  8 11 15 11 11 12 17 16 12 15  6 18 15 11 13 11 12 18 11  9  6 11 20
 14  7 13 13 10 11 13 10 15 15  9 16 11 11  9  9 10 15 12  6  8 16 15 10
  5 14 11 10 10 11 10  5 12 11  6 15 10  8  6 14 10  7  8 18  6 10 14 10
 15 10 14  8  5 17 14  6 18 11  8 18 13 16 19 10 13 19  9 16 14 13  8 13
 15 15 13 13  8 12 11  9  0 18  0  0 12 11  0  0  0  0 12 15  0  9 11 13
  0 11  0 11  0 10  0 14 10  0 12  8 13 10 15 12  0  7  0 10  7 12 10 16
  0 14  0 16 10  0  9  9 11  6  9 11  8 12 17  8 12 11 11 15  9 10 13  9
  8 10 14 15 16 10 18 10 16 10 10  6 11  9  7 13 10  7  8 13 14  8 10 15
  4  8  8 10  6  0 17 13 14  7 15 12  9 12 14 11  9 13  6 10 13 12 11  0
 12 12  0 12  0 18 13  8  5 15  8 10  8  8 12  8 13 11 14  0 18  8 12  9
  0 17 10 11 10  0  9 14 11 14 10 12  9  